name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream changes
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/sambecker/exif-photo-blog.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }} # 同样建议使用 PAT
